# 全局 Gradle 配置
# 注意：本工程刻意不使用 AndroidX 的 Jetifier（无老库），保持构建更快。

org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=false
